### ISSUE TITLE
Auto language detection

### ISSUE THREAD

**Issue by mfbehrens99** [matze-dd/YaLafi#155]
Hi,

LanguageTool is able to decide on its own what language to use if no language is provided.

I suggest to just set the default language to an empty string and filter this argument if nothing is provided so no language argument is sent to the server and LanguageTool will figure the language out for itself

It would be nice if somebody could give me some feedback. Then I can also implement the feature. It shouldn't be too difficult ;D

Best,
Michael

**Comment by mfbehrens99** [comment]
Update: Its actually not true what I wrote, but you can just set language to `auto` by default

**Comment by matze-dd** [comment]
Thanks for that idea! :)

But actually, we might create some problems. The filter uses the specified language to initialise some language-dependent values like equation replacements or meaning of a macro like `"'` (German right double quotes).

Furthermore, I do not know, how dependable LT's detection mechanism is. If you use 'babel' to specify the document language, then option --multi-language should do the job.

**Comment by mfbehrens99** [comment]
I think that the LanguageTool language detection works pretty good as long as you enter more than one word (I don't think any software or human can determine the language from one word)

But the macros might be a severe issue.

Maybe we could add a new argument to the shell command like `--lt-auto-language`. If this tag is set Yalafi would just pass `language=auto` to LT. If you don't want to specify a language you can just do something like `python -m yalafi.shell --lt-auto-language <file>`. The default language would be en-GB however auto is passed to the LT server.

I think this would guaranty full backwards compatibility but still implement the feature. What do you think about this?

**Comment by matze-dd** [comment]
> The default language would be en-GB however auto is passed to the LT server.
> I think this would guaranty full backwards compatibility but still implement the feature. What do you think about this?

This would still leave the problem that language-dependent settings in the filter (see `init_parser_languages()` in yalafi/parameters.py) would stay at English, even if LT detects another language.
