### ISSUE TITLE
Reference to atom plugin `linter-yalafi`

### ISSUE THREAD

**Issue by mfbehrens99** [matze-dd/YaLafi#159]
Hi, I created an atom plugin called `linter-yalafi` to check LaTeX files in Atom using YaLafi. It would be great If this project would appear next to the other YaLafi plugins in the `README.md`

**Comment by mfbehrens99** [comment]
![image](https://user-images.githubusercontent.com/58851724/105460905-bfeba380-5c8c-11eb-9e51-ea7dd438897e.png)

**Comment by matze-dd** [comment]
Thanks! I'll have a look at it.
