### ISSUE TITLE
Add support for `cleveref` package

### ISSUE THREAD

**Issue by torik42** [matze-dd/YaLafi#161]
I would like to add support for the [`cleveref`package](https://ctan.org/pkg/cleveref). It defines commands `\cref{…}` and similar that automatically expand to `equation \ref{…}`. The expansion depends on a lot of things and one can even customize it in the preamble. That’s why I don’t want to build all the commands again in YaLafi.

Instead, there is a package option called `poorman`. Here is a part of the documentation (page 23 in the documentation)
> When the `poorman` option is supplied, your document will be processed as normal. But in addition, a sed script will automatically be written, containing rules for replacing all the `cleveref` commands with the LaTeX code that they would produce, and using the standard `\ref` command to produce the crossreferences themselves. I.e. the script rewrites your document as you would have done if you had had to do it manually!

Here is a small example
`test.tex`:
```latex
\documentclass{scrartcl}

\usepackage[poorman]{cleveref}

\begin{document}
  Let
  \begin{equation}\label{eq:a}
    a = 1
  \end{equation}
  and
  \begin{equation}\label{eq:b}
    b = 2.
  \end{equation}
  From \cref{eq:a,eq:b} it follows that $a+b=3$.
  \Cref{eq:a} also yields $2a=2$.
\end{document}
```
the created `test.sed`:
```sed
s/\\cref{eq:a,eq:b}/\\cref@equation@name@plural \\nobreakspace \\textup {(\\ref {eq:a})}\\crefpairconjunction \\textup {(\\ref {eq:b})}/g
s/\\Cref{eq:a}/\\Cref@equation@name \\nobreakspace \\textup {(\\ref {eq:a})}/g
[...]
s/\\crefpairconjunction/ and\\nobreakspace /g
[...]
s/\\cref@equation@name@plural /eqs\./g
s/\\Cref@equation@name /Equation/g
[...]
s/\\usepackage\(\[.*\]\)\{0,1\}{cleveref}//g
```
and the new file:
```latex
\documentclass{scrartcl}



\begin{document}
  Let
  \begin{equation}\label{eq:a}
    a = 1
  \end{equation}
  and
  \begin{equation}\label{eq:b}
    b = 2.
  \end{equation}
  From eqs.\nobreakspace \textup {(\ref {eq:a})} and\nobreakspace  \textup {(\ref {eq:b})} it follows that $a+b=3$.
  Equation\nobreakspace \textup {(\ref {eq:a})} also yields $2a=2$.
\end{document}
```

As long as one does not add new references, the `sed` script will also work for a modified version of the latex source file. Hence, I would like to parse the `sed` file if `cleveref` is used (with `poorman` option and the `sed` file is available) such that YaLafi does the replacements and keeps track of the positions in the original source file.

Maybe one can define a macro for each `cleveref` command which then checks whether the argument given is already specified in the `sed` file. Is there already a clever way to load further files at runtime (e.g. only if `\usepackage[poorman]{cleveref}`is used) if it is not just a file with LaTeX commands?

What do you think?

**Comment by torik42** [comment]
Maybe the easiest solution to define the macros is to apply the `sed` script to the commands and then use YaLafi to remove the remaining commands, e.g. `\nobreakspace`, `\textup{…}`, `\ref{…}`.

**Comment by matze-dd** [comment]
Thank you for the idea and the detailed description! I'll have a look at it. Please give me some time to think it over.

**Comment by matze-dd** [comment]
> Maybe one can define a macro for each cleveref command which then checks whether the argument given is already specified in the sed file. Is there already a clever way to load further files at runtime (e.g. only if \usepackage[poorman]{cleveref}is used) if it is not just a file with LaTeX commands?
> What do you think?

Yes, this seems to be a clever idea. It should be feasible.

You can read a file with
```
    ok, txt = parser.read_macros(file_name)
```
where `ok` is True if the file could be read, and `txt` is the content as string. The `parser` object is available both while initialising the module and in a macro handler function.

After you have retrieved the replacement string for a concrete `\cref` (or similar) from your database, you can convert the string to a token list with
```
    toks = self.parms.scanner.scan(replacement_string)
```
Before the macro handler function returns the token list, it has to correct the token positions to the position of the `\cref` (or similar) macro, which is given in the last function argument `pos`. For instance, you could say
```
    for t in toks:
        t.pos = pos
```
The tokens you return from the handler function are pushed back and parsed as normal, afterwards. BTW, `\nobreakspace` is missing in the standard macro collection of yalafi/parameters.py.

> Maybe the easiest solution to define the macros is to apply the sed script to the commands and then use YaLafi to remove the remaining commands, e.g. \nobreakspace, \textup{…}, \ref{…}.

Yes, then you would not need to parse the `sed` script and build up a database. The overhead from calling `sed` on each macro invocation might be acceptable.

**Comment by matze-dd** [comment]
Did forget something. If you write tests, then you have to provide the function `read_macros()` to the parser's constructor. Test `test_2()` in `tests/test_special.py` shows an example.

**Comment by torik42** [comment]
Thank you for this detailed input. It is very helpful. I decided to read the `sed` script and build Macros out of that. The simple ones look like
```python
Macro(parser.parms, '\\Cref@equation@name', args='', repl='Equation')
```
The more complicated `\cref` has a replacement function that check whether the given argument is in some dictionary.

So far, I read the `sed` script using another Macro `\LTReadSed` which has the file name as its argument. It then creates all necessary macros. Hence, I can only define the `\LTReadSed` Macro in `init_module`. How do I get my new macros registered? If you want, you can already have a look here torik42/YaLafi@dab1da96f6729c18e7bb8767b51a6cca317c73bd.

**Comment by matze-dd** [comment]
> How do I get my new macros registered? If you want, you can already have a look here torik42/YaLafi@dab1da9.

The way as in line 40 of torik42/YaLafi@dab1da9 should work. I think there is a typo at line 90 (praser instead of parser).

In order to avoid that the end user is exposed to exception messages, I have encapsulated the module loading in a try block starting at line 68 in method `init_package()` in file `yalafi/parser.py`. If you remove this exception catching, then this may help in debugging.

**Comment by matze-dd** [comment]
Ah, now I did really understand. You want to define `\cref` etc. inside of `h_read_sed()`.

You may have a look at line 44 in `h_newcommand()` in file `yalafi/handlers.py`. You can set `repl` as in your line 84, and `scanned=True` is redundant, as far as I can see.

**Comment by torik42** [comment]
> I think there is a typo at line 90 (praser instead of parser).

You are right. But this function, of course, wasn’t executed so far.
 
> In order to avoid that the end user is exposed to exception messages, I have encapsulated the module loading in a try block starting at line 68 in method `init_package()` in file `yalafi/parser.py`. If you remove this exception catching, then this may help in debugging.

Yes, I have seen that and removed it locally.

> Ah, now I did really understand. You want to define `\cref` etc. inside of `h_read_sed()`.
>
> You may have a look at line 44 in `h_newcommand()` in file `yalafi/handlers.py`. You can set `repl` as in your line 84, and `scanned=True` is redundant, as far as I can see.

Indeed. I will have a look there.

**Comment by matze-dd** [comment]
> You are right. But this function, of course, wasn’t executed so far.

Yes. :) I didn't know whether you already turned off the exception catching during module initialisation, so just wanted to point at each possible failure reason.

**Comment by torik42** [comment]
I have a new problem. May you could help me again.
I now add all the macros using
```python
parser.the_macros['<command>'] = Macro(…)
```
I start with the fixed ones, e.g.
```python
Macro(parser.parms, '\\Cref@equation@name', args='', repl='Equation')
```
and add `\Cref`afterwards.

Running `YaLafi` with the document from my [initial post](https://github.com/matze-dd/YaLafi/issues/161#issue-792771804) replaces 
```latex
\Cref{eq:a}
```
with
```latex
\Cref@equation@name \nobreakspace \textup {(\ref {eq:a})}
```
but does not apply the macro replacing `\Cref@equation@name`. Do I miss something obvious here?

Also, is there an option to get the Output which `YaLafi` sends to LangueTool? This would be very helpful for debugging.

**Comment by matze-dd** [comment]
Quick first reply:
> Also, is there an option to get the Output which YaLafi sends to LangueTool? This would be very helpful for debugging.

You can use `python -m yalafi test.tex` to get the plain text sent to LanguageTool. For options, see [here](https://github.com/matze-dd/YaLafi#command-line-of-pure-filter).

**Comment by matze-dd** [comment]
> ... but does not apply the macro replacing \Cref@equation@name. Do I miss something obvious here?

I cannot find any obvious problem in your scheme. As a quick test, I wrote to t.tex
```
\newcommand{\nobreakspace} ~
\newcommand{\Cref@equation@name}{Equation}
\newcommand{\Cref}[1]
    {\Cref@equation@name \nobreakspace \textup {(\ref {#1})}}
\Cref{ref:a}
```
and run `python -m yalafi t.tex` with result
```
Equation (0)
````
At least in principle, it should work.

**Comment by torik42** [comment]
Thanks a lot. I think I found my mistake: Too many escaped backslashes.

**Comment by matze-dd** [comment]
Excellent! Without finding own mistakes, it's only half of the fun.
