### ISSUE TITLE
Add contribution guideline and pull request template for adding packages

### ISSUE THREAD

**Issue by torik42** [matze-dd/YaLafi#167]
I myself had to look into old pull requests to see what needs to be done. I had the `yalafi/packages/package_name.py` before. But also other things need to be done. And still, I missed some.

It would be super nice, to have a short list on what needs to be done and also a checkmark list in some pull request template. For example

> Add support for LaTeX package .
> 
> **Checklist**
> - [ ] Add a file `yalafi/packages/package_name.py` implementing all the needed commands of the package.
> - [ ] Add a file `yalafi/tests/test_packages/test_package_name.py` testing all the features.
> - [ ] Add the package and implemented features to `list-of-macros.md` and reference it in the Contents section.
> - [ ] Add the package to the default package list in `yalafi/packages/__init__.py`.

Hopefully, I did not forget a step. The same, of course, would be nice for document classes.

**Comment by matze-dd** [comment]
Thank you for this useful feedback and equally useful proposal! I'll definitely come back to this issue.
