### ISSUE TITLE
Add support for subfiles documentclass

### ISSUE THREAD

**Issue by pmeckoni** [matze-dd/YaLafi#185]
The [`subfiles`](https://www.ctan.org/pkg/subfiles) documentclass can be used to split a long document in to subfiles.  ~~and also allowing~~ It also allows each subfile to be compiled on its own when needed. 

Please extend support for `subfiles` documentclass.

**Comment by matze-dd** [comment]
Thank you for the feedback!

I've just added a [section on multi-file projects](https://github.com/matze-dd/YaLafi#multi-file-projects) in README.md. Could you please have a look at it? For the basic usage of package subfiles, the following appears to me.
- The basic LaTeX filter only needs to ignore macro \\subfile, just as it currently does for \\input.
- For yalafi.shell to be used with option --include for recursive file checking, we also only need to add macro \\subfile to the list of macros that indicate file inclusion.

Do I miss something (do not use subfile myself)? Have you other macros for more advanced applications in mind, which should be covered?

**Comment by pmeckoni** [comment]
You are right on both of your bullet points. 
An addition is that the newer version of subfile has added `\subfileinclude` corresponding to `\include` while `\subfile` corresponds to `\input`.

The usepackage declarations remain in the main file and are absent in the subfile. So while analyzing only the subfile through yalafi, does it need to know the different `\usepackage` macros used?

Now, if you see the screenshot, it identifies spelling mistakes in labels and cleveref macros that I thought it was supposed to ignore. I am assuming it is because of the subfile.

<img width="600" alt="Screenshot_20210203_131722" src="https://user-images.githubusercontent.com/15984653/106792179-d0eccb00-6623-11eb-891d-dd0c3000ef30.png">

**Comment by matze-dd** [comment]
> An addition is that the newer version of subfile has added \subfileinclude corresponding to \include while \subfile corresponds to \input.

OK, have added the package with both macros, and yalafi.shell will respect them on option --include.

> Now, if you see the screenshot, it identifies spelling mistakes in labels and cleveref macros that I thought it was supposed to ignore. I am assuming it is because of the subfile.

This perhaps happens, because package cleveref has not been loaded. Please see [here](https://github.com/matze-dd/YaLafi/blob/master/list-of-macros.md#package-cleveref). Loading main.tex as mentioned [here](https://github.com/matze-dd/YaLafi#multi-file-projects) does activate the package, if it is in the preamble. If you run into problems, give me a ring; the implementation of cleveref is quite new.

> The usepackage declarations remain in the main file and are absent in the subfile. So while analyzing only the subfile through yalafi, does it need to know the different \usepackage macros used?

See above. Additionally, you might want to make available own macros defined in the preamble.

**Comment by pmeckoni** [comment]
This means if I'm only checking errors in the subfile and not the mainfile, then it will continue to show me errors inside cleveref macros.

To improve this working, when only the subfile is being checked, all the packages available in the mainfile should be loaded too.

BTW, this is great work. Keep it going.

**Comment by matze-dd** [comment]
> Can this be auto-detected instead of giving the option?

Good question. Certainly, there might be a way. But in the current modular structure, a macro like \\cref is only available and thus can detect the problem, if the package already has been loaded. I'd like to keep this structure.

> BTW, this is great work. Keep it going.

Thanks. :) I'm glad that it is useful for you.
