### ISSUE TITLE
Errors on `\graphicspath`

### ISSUE THREAD

**Issue by mfbehrens99** [matze-dd/YaLafi#186]
Hi I am getting some YaLafi errors on a `\graphicspath` command. 
![image](https://user-images.githubusercontent.com/58851724/106740594-e90c1c80-661a-11eb-9e6c-13f63624eeaf.png)
Is this a problem with my YaLafi configuration or is this a bug? This part is even before the `\begin{document}`, don't know if this matters
Thanks
Michael

**Comment by matze-dd** [comment]
Thanks for spotting this!

Could you please help me (do not use these tikz packages myself)? I assume that tikz, which is loaded by circuitikz, should load graphicx, which should define \\graphicspath. Is this correct? Then I will add \\graphicspath to graphicx and cause tikz to load graphicx.

**Comment by mfbehrens99** [comment]
`graphicx` is imported in the `.cls` class file, so I don't think it is imported by `tikz`

**Comment by matze-dd** [comment]
OK, I have added the macro to graphicx and tikz.
