### ISSUE TITLE
Add Custom ignore List

### ISSUE THREAD

**Issue by jonaschl** [matze-dd/YaLafi#187]
Hi,

first thanks for this project it does it job already very well. I know that I can skip certain words with \LTskip{}, but how can I add some custom words which are spelt correctly? Something like proper names? It would be cool if this is usable with the "server" version.

I have searched the web and the API of LanguageTool but there do not seem to be an easy way for this.

Greetings Jonatan

**Comment by matze-dd** [comment]
> ... first thanks for this project it does it job already very well.

Thank you! I'm glad that it is useful for you.

> but how can I add some custom words which are spelt correctly? Something like proper names?

You may have a look [at his section](https://github.com/matze-dd/YaLafi#phrase-replacement-in-the-plain-text). You can replace words or even remove them. In my own applications, I tend to replace them, for instance, by more common proper names.

**Comment by matze-dd** [comment]
Please feel free to re-open, if you want to continue the discussion.
