### ISSUE TITLE
Provide option to change ltcommand

### ISSUE THREAD

**Issue by oponkork** [matze-dd/YaLafi#19]
In `yalafi/shell/shell.py`, the language tool command is hardcoded, which works well if you directly
download languagetool. I installed it via my package manager, which gives me a binary instead of
jarfile in `/usr/bin`, and other files are located in `/usr/share/languagetool/`. In order to get it working I had to do the following change in `yalafi/shell/shell.py`
```python
# ltcommand = 'java -jar languagetool-commandline.jar --json --encoding utf-8'
ltcommand = 'languagetool --json --encoding utf-8'
```
I was then able to generate a report by using the following command
```bash
python -m yalafi.shell --lt-directory /usr/share/languagetool/ --output html draft.tex > draft.html
```
It would be nice to provide a command line option to change ltcommand as well.

**Comment by matze-dd** [comment]
You have the privilege of being the frist who opens an issue "from outside" ;-). After the next commit to the repository, it should be possible to say
```
python -m yalafi.shell --lt-directory /usr/share/languagetool/ \
        --lt-command languagetool --output html draft.tex > draft.html
```

**Comment by oponkork** [comment]
> Thank you for the input. You have the privilege of being the frist who opens an issue "from outside" ;-).
Thanks for your quick reply. I got to know about yalafi from lurking at vimtex repository. Thought of trying it out.

>  After the next commit to the repository, it should be possible to say
> ```
> python -m yalafi.shell --lt-directory /usr/share/languagetool/ \
>         --lt-command languagetool --output html draft.tex > draft.html
> ```
Oh cool that was quick. I will update my installation and get back to you if I have any issues.

Once again, thanks a lot.

**Comment by matze-dd** [comment]
@oponkork: Could you please have a look at Issue #60? Would this be OK for you? More specifically, does `--lt-directory . --lt-command languagetool` work in your case?

Thanks in advance!
