### ISSUE TITLE
Treat \paragraph(*) like \section or \subsection

### ISSUE THREAD

**Issue by mfbehrens99** [matze-dd/YaLafi#192]
Treat `\paragraph`(`*`) like `\section` or `\subsection`

![image](https://user-images.githubusercontent.com/58851724/106948056-8c4c5700-672b-11eb-926d-75e47148293a.png)
Falls das das Problem ist, sollte es nicht so schwer zu beheben sein ;)

**Comment by matze-dd** [comment]
Wird gemacht. Morgen oder übermorgen ;)
