### ISSUE TITLE
positional argument of figure environment

### ISSUE THREAD

**Issue by schrc3b6** [matze-dd/YaLafi#30]
Hi,

let me thank you at first for this great project and especially the good vim and languagetool integration.

I've noticed that yalafi leaves the positional argument of the figure environment in.

Input:
```
\begin{figure}[h]
    \centering
    \includegraphics[width=0.7\linewidth]{./image.png}
\end{figure}
```
Output: ` [h]`

I'm using Yalafi version 1.1.1 (from pip) with the Languagetool Plugin in vim.

Best Regards
Max

**Comment by matze-dd** [comment]
Thank you for the kind words and for spotting the problem. Obviously, a lot of standard macros and environemnts are not yet properly handled "out-of-the-box". I'm working on a structured solution (Issue #28).

Can you edit file `yalafi/parameters.py`? It should be in a directory like indicated by the third point in section "Installation" of README.md. Above the line (#125 in v.1.1.1)
```
        Environ(self, 'minipage', args='A'),
```
you could add
```
        Environ(self, 'figure', args='O', add_pars=False),
```
The `args='O'` specifies the optional argument. It is simply dropped, as there is no replacement specification. The `add_pars=False` avoids that paragraph breaks are pre- and appended to the environment.

I will include that in the next version. If you encounter more problems, you may have a look at "Inclusion of own macros" of README.md.
Independently of that, I appreciate any further observations.

**Comment by schrc3b6** [comment]
Thanks. This fixed it :)

I also noticed that the phantom macros are not parsed correctly.
However since there are three phantom commands (\phantom, \vphantom, \hphantom) it would be great if it was possible to use a regex like ([v,h]?phantom) for the name parameter.

I also noticed that in the Readme.md (https://github.com/matze-dd/YaLafi#definition-of-macros) says: name: macro name with '\'
but in the definition of environment it's not stated that the backslash should not be included.

**Comment by matze-dd** [comment]
> I also noticed that the phantom macros are not parsed correctly.

Thanks for this feedback. One could simply say `\newcommand{\phantom}[1]{\;}`, and the same for \\hphantom. For the proofreader, space is space. A more elaborate definition on Python level would use a small handler function that checks, whether the argument really expands to a string of non-zero length.

What do you think of \\vphantom? How should it behave? I have never used it in text mode and cannot construct a useful example.

>  However since there are three phantom commands (\phantom, \vphantom, \hphantom) it would be great if ...

For this project, I have opted to use as little as possible of the magic regex tricks from [Tex2txt](https://github.com/matze-dd/Tex2txt). The price is some boilerplate code.

> I also noticed that in the Readme.md ...

Thanks once again. I'll correct that.

**Comment by schrc3b6** [comment]
> What do you think of \vphantom? How should it behave? I have never used it in text mode and cannot construct a useful example.

Me neither I've only used it in math mode. But theoretically it just should be removed (without inserting a space).
