### ISSUE TITLE
lt_command not working with vimtex

### ISSUE THREAD

**Issue by piyueh** [matze-dd/YaLafi#63]
Hi, thanks for this great tool!

I noticed the recent PR #62 and issue #60, allowing users to specify alternative `languagetool` command. I replaced the original `vlty.vim` in ***vimtex*** with the one that comes with YaLafi to try it. Based on README, I commented out `g:vimtex_grammar_vlty.lt_directory` and only specified `g:vimtex_grammar_vlty.lt_command`. However, ***vimtex*** then complained `lt_directory path not valid`.

I'm not familiar with vim script, but I think it has something to do with the checking code [here in `vlty.vim`](https://github.com/matze-dd/YaLafi/blob/f932ce9f78524d7b5ba7b6b55eea7370297a0600/editors/vlty.vim#L39-L43)?

https://github.com/matze-dd/YaLafi/blob/f932ce9f78524d7b5ba7b6b55eea7370297a0600/editors/vlty.vim#L39-L43

**Comment by matze-dd** [comment]
> Hi, thanks for this great tool!

Thanks :)

> ... However, vimtex then complained lt_directory path not valid. I'm not familiar with vim script, but I think it has something to do with the checking code here in vlty.vim? ...

Oh yes, this is very probably wrong. I will fix that next week.
Thank you for pointing to the problem!

**Comment by matze-dd** [comment]
OK, at least on my Arch Linux, it does now work. Actually, there was one more issue in vlty.vim.

Please let me know, if there is still a problem.
