### ISSUE TITLE
bibitem isn't processed as expected

### ISSUE THREAD

**Issue by petRUShka** [matze-dd/YaLafi#80]
Suppose we have bibliography in our tex-file:

```
\begin{thebibliography}{99}
  \bibitem{paper_name}
\end{thebibliography}
```

yalafi will process `paper_name` as sentence but not the technical label. So one sees an error on that line.

**Comment by petRUShka** [comment]
Same for macros `\bibliographystyle{maik}`.

**Comment by matze-dd** [comment]
Thanks for reporting!

I'm wondering: are these standard LaTeX macros or are they only loaded with package biblatex?

**Comment by petRUShka** [comment]
@matze-dd looks [like standard](https://en.wikibooks.org/wiki/LaTeX/Bibliography_Management#Embedded_system).
